services:
  db:
    image: postgres
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  script:
    build: .
    restart: always
